/* Create the CUSTOMERS1 data table */
CREATE TABLE CUSTOMERS1
(
	CustNo NUMBER(10),
	FirstName VARCHAR2(25) NOT NULL,
	LastName VARCHAR2(25) NOT NULL,
	Address VARCHAR2(100),
	City VARCHAR2(45),
	AddrState VARCHAR2(2),
	Zip VARCHAR2(5),
	Phone VARCHAR2(10),
		CONSTRAINT CUSTOMERS1_CustNo_pk PRIMARY KEY(CustNo),
		CONSTRAINT CUSTOMERS1_state_leng CHECK(length(AddrState) = 2)
);

/*Create the VEHICLES1 data table */
CREATE TABLE VEHICLES1
(
	SerialNo VARCHAR2(10),
	CustNo NUMBER(10) NOT NULL,
	Year NUMBER(4, 0),
	Model VARCHAR2(25),
	LicenseNo VARCHAR2(6),
	State VARCHAR2(2),
	Cylinder NUMBER(1, 0),
	Make VARCHAR2(20),
		CONSTRAINT VEHICLES1_SerialNo_pk PRIMARY KEY (SerialNo),
		CONSTRAINT CUSTOMERS1_CustNo_fk FOREIGN KEY (CustNo)
			REFERENCES CUSTOMERS1(CustNo)
);

/* Create the REPAIRORDERS1 data table */
CREATE TABLE REPAIRORDERS1
(
	OrdNo VARCHAR2(10),
	SerialNo VARCHAR2(10),
	Odometer VARCHAR2(10),
	repOrdDate DATE DEFAULT SYSDATE,
		CONSTRAINT REPAIRORDERS1_OrdNo_pk PRIMARY KEY (OrdNo),
		CONSTRAINT VEHICLES1_SerialNo_fk FOREIGN KEY (SerialNo)
			REFERENCES VEHICLES1 (SerialNo)
);

/* Create the PARTSUSED data table */
CREATE TABLE PARTSUSED1
(
	OrdNo VARCHAR2(10),
	PartNo VARCHAR2(10),
	QtyUsed VARCHAR2(3),
		CONSTRAINT PARTSUSED1_PartNo_pk PRIMARY KEY (PartNo),
		CONSTRAINT REPAIRORDERS1_OrdNo_fk FOREIGN KEY (OrdNo)
			REFERENCES REPAIRORDERS1 (OrdNo)
);

/* Create the Part data table*/
CREATE TABLE PARTS1
(
	PartNo VARCHAR2(10),
	PartDesc VARCHAR2(40),
	UnitsInStock VARCHAR2(12),
	UnitPrice NUMBER(15, 2),
	UnitSize VARCHAR2(3),
		CONSTRAINT PART1_PartNo PRIMARY KEY (PartNo)
);
